### ISSUE TITLE
menemonic phase

### ISSUE THREAD

**Issue by lordragnarok** [Coding-Enthusiast/FinderOuter#16]
I used the option to recover the menemonic phase for 2 missing words from the atomic wallet, I ran the program and it gave an error. do you know why?

i used m/44'/0'/0'/0/0

**Comment by Coding-Enthusiast** [comment]
What was the error?

**Comment by lordragnarok** [comment]
of the failure and the red x appears, he couldn't find out. Do not place the correct path: m / 44 '/ 0' / 0 '/ 0/0. So I think it went wrong, how do I know that I am putting the correct path?

**Comment by lordragnarok** [comment]
![image](https://user-images.githubusercontent.com/77459321/105197591-87788800-5b1b-11eb-8180-1c4ad3cdeae8.png)
this image is from an example in the program, it worked, but to find 2 words, it takes so long?

**Comment by Coding-Enthusiast** [comment]
> how do I know that I am putting the correct path?

You have to figure it out based on the wallet that you were using. Sometimes their documentation mentions the derivation paths. Otherwise go to a forum like bitcointalk.org and ask people there.

> it takes so long?

Generally for smaller number of words in mnemonic (12 here) and for each extra index in the path the process becomes slower because the number of operations it has to perform increases. 
But also there is a known issue (#9) that slows down the process more when the path or the child key itself is not hardened.

**Comment by lordragnarok** [comment]
hello, I tried to recover 2 characters from the menemonic phase of the atomic portfolio, as tests. I took p path on their website and it is correct. However, the program ran for 5 hours and gave an error.

![image](https://user-images.githubusercontent.com/77459321/105258037-abfa5180-5b67-11eb-9657-6b50aba8a1b1.png)

**Comment by Coding-Enthusiast** [comment]
Your path has an extra 0 in it. Change it to `m/44'/0'/0'/0/` and it should work.  
Here is an example from their website: `round blade service action buzz unlock ladder knee promote proud dutch *`, address = `163e6h58v579YRcfttxoqWN9aNkMLuSyrc`, type = `AddrComp`, path = `m/44'/0'/0'/0/` index = `0` Hardened key = `false` 

Maybe I should remove the key/address index textbox and consider the path to be the full path instead of being the path to the extended child key?

**Comment by lordragnarok** [comment]
Ok, in site the atomic wallet :

![image](https://user-images.githubusercontent.com/77459321/105347606-e85c9a80-5bc5-11eb-88a6-01c0c7f9656b.png)

**Comment by Coding-Enthusiast** [comment]
The key index is now a part of the path instead of being in a separate textbox b3e285d87bc164aaa59ab4eba05ab5c8481140ef it should remove the confusion about derivation paths.  
I'm closing this issue but feel free to discuss it.
