### ISSUE TITLE
Windows Build > Debug Mode Warning

### ISSUE THREAD

**Issue by sezginyildirim91** [Coding-Enthusiast/FinderOuter#23]
I created it from the release version. I'm getting a debug mode warning and I don't know how to fix this.

![Debug Mode](https://i2.paste.pics/d6e19fd9af23808133955a684d984cb0.png)

**Comment by Coding-Enthusiast** [comment]
> I created it from the release version. I'm getting a debug mode warning and I don't know how to fix this.

You should set the dot net "build configuration" to `release`.  

- Using .Net core CLI that means `dotnet build --configuration Release`  read more [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build) 
- Using Visual Studio you have to simply change solution configuration from standard ToolBar to `Release` 

![config](https://user-images.githubusercontent.com/20510382/113508732-d94f7c80-9566-11eb-96e5-0d97bbef6b2a.jpg)

Then it is best to navigate to the build location (eg. `..\FinderOuter\Src\FinderOuter\bin\Release\net5.0`) and run the FinderOuter from there instead of running it using Visual Studio itself to avoid attaching a debugger that could slow it down.

**Comment by sezginyildirim91** [comment]
Problem solved. Thank you.

`dotnet build .\FinderOuter.sln --configuration Release`
