### ISSUE TITLE
Custom Derivation Paths

### ISSUE THREAD

**Issue by anarchymachines** [Coding-Enthusiast/FinderOuter#28]
First off, this is great. So easy to get up and running (the binary works like a charm) and the instructions are easy to understand. Very refreshing for avid tinkerers like myself who are not quite computer scientists.

Anyway, I was wondering if there are any plans to allow entering a custom derivation path? Or at least part of 1? Some wallets of course use non-standard ones. And I know that altcoins are not supported, but a lot of them would still be compatible with the software as-is if we could just change the derivation path. For instance, I'm trying to recover an Ethereum key and I know the mnemonic (I think), and I have the public key, which is the same format as a Bitcoin public key. If I could set the path to something like m/44'/60'/?/? or something like that, I could maybe potentially use it for recovering that Ethereum key (I think...please correct me if I'm wrong about that). I don't really mind if I have to run the thing for hours and hours, if that's what it takes. 

Anyway, just thought I'd throw that out there. Thanks again for making this tool!

**Comment by Coding-Enthusiast** [comment]
> First off, this is great. So easy to get up and running (the binary works like a charm) and the instructions are easy to understand. Very refreshing for avid tinkerers like myself who are not quite computer scientists.

Thanks for the feedback.

> Anyway, I was wondering if there are any plans to allow entering a custom derivation path?

Which recovery option are you talking about?   
The _Missing Mnemonic_ option already has it. The last textbox is editable like others and you can set any derivation path you like. It is also very flexible for both length and hardened indicator you can use `'` or `h` or `H` like below:  
![derivpath](https://user-images.githubusercontent.com/20510382/120896534-4222a600-c637-11eb-84b0-c6a984b0bca3.jpg)

If it is the _Missing BIP32 Path_ option, I'm afraid the option is currently a very limited as it only goes through a handful of popular derivation paths. I recently found a better list which I'll update FinderOuter with for next version.   

> If I could set the path to something like m/44'/60'/?/? or something like that,

I'm afraid this won't work if the path is something other than the hard-coded list because each index is from 0 to 4.29 billion and if you were missing more than one it will be multiplied (ie. 2 missing is 4.29B<sup>2</sup>=18*10<sup>18</sup>) and it simply becomes impossible to check them one by one.

**Comment by anarchymachines** [comment]
Got it. Any chance you can share the list of paths you found?

**Comment by Coding-Enthusiast** [comment]
> Got it. Any chance you can share the list of paths you found?

https://walletsrecovery.org/
