### ISSUE TITLE
No optimization for missing chars in start of private key ??

### ISSUE THREAD

**Issue by mobinko** [Coding-Enthusiast/FinderOuter#68]
Hello 
my paper that i was wrote down private key is damaged so i lost some characters in the start of privatey key. i searched for how private keys work and i know my privatey key starting with 5 and it is 51 character long , the format is below :
5**********????????????????????????????????????????
the ? means known characters , so i tried with FinderOuter but there was no optimization for my case and in normall way it takes more than 100 years to recover . what can i do now ? 
it is a large money in wallet and i need help with that

**Comment by Coding-Enthusiast** [comment]
The optimization used for missing characters at the end won't work for the characters at the start because of the way WIFs are converted to integer. A character near the beginning has a range in 58<sup>50</sup>.  
Check out other projects like https://github.com/PawelGorny/WifSolverCuda that use different approaches and also support GPU.

**Comment by mobinko** [comment]
i have rx6600 so the program is just for cuda devide ?

**Comment by Coding-Enthusiast** [comment]
I believe so. You have to contact the developer, they also have other helpful projects.

**Comment by mobinko** [comment]
Thank you.
For last question , i used hashcat and it takes 290 days to recover my wallet . is "WifSolverCuda" faster than hashcat ?

**Comment by Coding-Enthusiast** [comment]
In some cases yes.
